[Behavior]
AutoSelectionDelay=600
BookmarkOpenMethod=current_tab
ConfirmDelete=true
ConfirmTrash=false
CtrlRightClick=false
NoUsbTrash=false
QuickExec=false
RecentFilesNumber=0
SelectNewFiles=true
SingleClick=false
SingleWindowMode=false
UseTrash=true

[Desktop]
AllSticky=false
BgColor=#000000
DesktopCellMargins=@Size(3 1)
DesktopIconSize=48
DesktopShortcuts=@Invalid()
FgColor=#ffffff
Font="Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
HideItems=false
LastSlide=
NoItemTooltip=false
OpenWithDefaultFileManager=false
PerScreenWallpaper=false
ScreenNames=@Invalid()
ShadowColor=#000000
ShowHidden=false
SlideShowInterval=0
SortColumn=name
SortFolderFirst=true
SortHiddenLast=false
SortOrder=ascending
TransformWallpaper=false
Wallpaper=
WallpaperDialogSize=@Size(700 500)
WallpaperDialogSplitterPos=200
WallpaperDirectory=
WallpaperMode=none
WallpaperRandomize=false
WorkAreaMargins=12, 12, 12, 12

[FolderView]
BackupAsHidden=false
BigIconSize=48
CustomColumnWidths=392, 92, 76, 164, 0, 0, 0, 0
FolderViewCellMargins=@Size(3 3)
HiddenColumns=4, 6, 7
Mode=detailed
NoItemTooltip=true
ScrollPerPixel=true
ShadowHidden=true
ShowFilter=false
ShowFullNames=true
ShowHidden=false
SidePaneIconSize=22
SmallIconSize=48
SortCaseSensitive=false
SortColumn=dtime
SortFolderFirst=true
SortHiddenLast=false
SortOrder=descending
ThumbnailIconSize=128

[Places]
HiddenPlaces=@Invalid()

[Search]
ContentPatterns=@Invalid()
MaxSearchHistory=0
NamePatterns=@Invalid()
searchContentCaseInsensitive=false
searchContentRegexp=true
searchNameCaseInsensitive=false
searchNameRegexp=true
searchRecursive=false
searchhHidden=false

[System]
Archiver=ark
FallbackIconThemeName=oxygen
OnlyUserTemplates=false
SIUnit=false
SuCommand=lxqt-sudo %s
TemplateRunApp=false
TemplateTypeOnce=false
Terminal=kitty

[Thumbnail]
MaxExternalThumbnailFileSize=-1
MaxThumbnailFileSize=30720
ShowThumbnails=true
ThumbnailLocalFilesOnly=false

[Volume]
AutoRun=false
CloseOnUnmount=false
MountOnStartup=true
MountRemovable=false

[Window]
AlwaysShowTabs=false
FixedHeight=480
FixedWidth=640
LastWindowHeight=1030
LastWindowMaximized=false
LastWindowWidth=934
PathBarButtons=true
RememberWindowSize=true
ReopenLastTabs=true
ShowMenuBar=false
ShowTabClose=true
SidePaneMode=places
SidePaneVisible=true
SplitView=false
SplitViewTabsNum=0
SplitterPos=161
SwitchToNewTab=true
TabPaths=/home/kirill/.dotfiles
