config_version = 14

[audio]
enable_sounds = true

[bar]
order = [ "my_noctalia" ]

    [bar.my_noctalia]
    background_opacity = 0.29999999329447746
    border = "primary"
    border_width = 0
    capsule_fill = "on_primary"
    capsule_foreground = "primary"
    capsule_opacity = 0.29999999329447746
    center = []
    concave_edge_corners = true
    end = [
        "media",
        "tray",
        "notifications",
        "clipboard",
        "keyboard_layout",
        "bluetooth",
        "input_volume",
        "volume",
        "power_profile",
        "battery",
        "brightness",
        "network",
        "spacer_1",
        "date",
        "spacer_1",
        "clock"
    ]
    font_family = "Maple Mono NF"
    font_weight = 700
    margin_ends = 0
    position = "bottom"
    radius_bottom_left = 0
    radius_bottom_right = 0
    scale = 1.1499999999999999
    shadow = false
    start = [
        "session",
        "control-center",
        "wallpaper",
        "widget",
        "screenshot",
        "bar_2",
        "spacer_1",
        "workspaces",
        "spacer_1",
        "taskbar"
    ]
    thickness = 38

[battery]
warning_threshold = 20

[control_center.calendar]
show_events_card = false

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "caffeine"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.29999999329447746
border = "primary"
border_width = 2.0
concave_edge_corners = false
icon_size = 32
launcher_position = "start"
magnification_scale = 2.0
margin_edge = 4
reserve_space = false
shadow = false
show_dots = true

[idle]
behavior_order = [ "screen-off", "lock", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 360.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 300.0

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = false
    timeout = 600.0

[lockscreen]
fingerprint = false
lock_before_suspend = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 702.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 544.0
    box_width = 800.0
    cx = 960.0
    cy = 428.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false

[notification]
filter_order = [ "filter" ]
layer = "overlay"
position = "bottom_right"

[plugin_settings."noctalia/timer"]
panel_placement = "floating"

[plugin_settings."oldirtty/color_picker"]
hyprpicker-lowercase = true

[plugin_settings."piero-93/battery-power-management"]
battery_device = "BAT1"
show_balanced_icon = true

[plugin_settings."thepunkoff/pomodoro"]
bypass-noctalia-sound-globals = true
use-bundled-alarm-sound = true
work-duration = 1

[plugin_settings."yuuto/calculator"]
panel_placement = "floating"

[plugins]
enabled = [ "yuuto/calculator", "oldirtty/color_picker" ]

[shell]
app_icon_color = "#FFFFFF"
app_icon_colorize = true
font_family = "Maple Mono NF"
panel_anchor_bar = "my_noctalia"
polkit_agent = true
popup_shadows = false
show_location = false

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    compact = true

    [shell.panel]
    borders = false
    shadow = false

    [shell.shadow]
    direction = "down_right"

[theme]
builtin = "Gruvbox"
community_palette = "Tokyo Night Storm"
custom_palette = "my_noctalia.moon"
mode = "dark"
source = "custom"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "kitty", "mango", "qt" ]
    community_ids = [ "telegram", "yazi" ]

[wallpaper]
directory = "/home/kirill/Downloads/wallpapers"

    [wallpaper.default]
    path = "/home/kirill/Downloads/wallpapers/wallhaven-mlgzzy_1920x1080.png"

    [wallpaper.last]
    path = "/home/kirill/Downloads/wallpapers/wallhaven-mlgzzy_1920x1080.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/kirill/Downloads/wallpapers/wallhaven-mlgzzy_1920x1080.png"

    [[wallpaper.favorite]]
    path = "/home/kirill/Downloads/wallpapers/869010-green-minimalist-wallpaper-top-free-green-minimalist-background.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kirill/Downloads/wallpapers/869013-minimalist-green-wallpaper-top-free-minimalist-green-background.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kirill/Downloads/wallpapers/wallhaven-1p55dw_1920x1080.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    custom_palette = "my_noctalia"
    palette_source = "custom"
    path = "/home/kirill/Downloads/wallpapers/wallhaven-4lvxjy_1920x1080.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    custom_palette = "my_noctalia.moon"
    palette_source = "custom"
    path = "/home/kirill/Downloads/wallpapers/wallhaven-mlgzzy_1920x1080.png"
    theme_mode = "dark"

[weather]
enabled = false

[widget.audio_visualizer]
bands = 48
mirrored = false
show_when_idle = true
width = 500

[widget.bar_2]
type = "yuuto/calculator:bar"

[widget.battery]
display_mode = "graphic"

[widget.bluetooth]
hide_when_adapter_off = true

[widget.brightness]
show_label = false

[widget.date]
format = "{:%d/%b}"

[widget.input_volume]
enabled = false
show_label = false

[widget.keyboard_layout]
show_glyph = false

[widget.launcher]
enabled = false

[widget.lock_keys]
display = "full"

[widget.media]
enabled = false

[widget.network]
show_label = false
vpn_status = "both"

[widget.spacer_1]
type = "spacer"

[widget.tray]
hide_passive = false

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.workspaces]
active_pill_size = 1.0
hide_when_empty = true
